# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Azure Storage

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  build-and-deploy:
    #environment:
     # name: github-pages
     # url: ${{ steps.deployment.outputs.page_url }}
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

      #- name: Login to Azure
      #  uses: azure/login@v1
      #  with:
      #   creds: ${{ secrets.AZURE_CREDS }}
        
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Deploy to Azure
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 'web'
          container_name: '$web'
          #account_name: ${{ secrets.AZ_STORAGE_ACCT }}
          connection_string: ${{ secrets.AZ_CONN_STR }}
          sync: 'true'